server:
  port: 8062
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: AnibalG
    password: agac1995
    driver-class-name: org.postgresql.Driver
   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
